name: Carlos Chida
favicon: null
layout_spectrum: 1
typography_spectrum: 0.67038
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8133625951595604
  lightness: 0.48416788689792156
  saturation: 0.307626286521554
  rhythmicContrast: 0.22386708948761225
purpose: []
